name: Reusable Workflow

on:
  # push:
  workflow_dispatch:
  # workflow_call:
  #   inputs:
  #     username:
  #       required: true
  #       type: string
        
jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - name: AWS login
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2


      - run: | 
          export 
          aws s3 ls
